# PostgreSQL StatefulSet
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-db
spec:
#  serviceName: postgresql-db-service
  selector:
    matchLabels:
      app: postgresql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
        - name: postgresql-db
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_PASSWORD
              value: pass
#      hostNetwork: true
#      dnsPolicy: ClusterFirstWithHostNet
---
# PostgreSQL StatefulSet Service
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgresql-db
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
---
#kind: Service
#apiVersion: v1
#metadata:
#  name: postgres
#spec:
#  type: ExternalName
#  # https://docs.docker.com/docker-for-mac/networking/#use-cases-and-workarounds
#  externalName: host.docker.internal
#  ports:
#    - name: port
#      port: 5432
